# Site settings
title: Orzlab Study
email: contact@orzlab.net
baseurl: ""
url: "http://study.orzlab.net/"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Collections
collections:
  courses:
    output: true
    permalink: /:collection/:path/
    
# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "course"
